title: The Phisherman
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8820336
  brandStrength: 0.875
  lightness: 0.9396454
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#750f0b'
    - '#c0c0c0'
    - '#878787'
  rhythmicContrast: 0.4318996
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: The Phisherman
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.74819
layout_spectrum: 0.74639
