name: The Phisherman
favicon: null
layout_spectrum: 0.74639
typography_spectrum: 0.04608847270719707
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#750f0b'
    - '#c0c0c0'
    - '#878787'
  brandStrength: 0.8752675603609532
  lightness: 0.9396454077214003
  saturation: 0.8820335837081075
  rhythmicContrast: 0.06185376225039363
purpose: []
